### ISSUE TITLE
Can I add your json2hat script to this GrimoireLab list?

### ISSUE THREAD

**Issue by jgbarah** [lukaszgryglicki/bitergia_deployment#1]
I've seen your [json2hhat](https://github.com/lukaszgryglicki/bitergia_deployment/blob/master/cmd/json2hat/json2hat.go) Go script, for (if I'm not wrong) injecting GitHub identities in SortingHat. 

Would you mind if we include it in the list of 3rd party components for GrimoireLab? We're trying to have a list of components (panels, scripts, and other stuff) that could be useful to GrimoireLab users, and your script seems to be in this category.

**Comment by lukaszgryglicki** [comment]
Sure, go ahead. It imports `github_users.json` from `cncf/gitdm` into a SortingHat DB. 
Let me know if you have any questions.

**Comment by jgbarah** [comment]
Done in chaoss/grimoirelab#157. Feel free to comment on the pr if you want. Thanks!

**Comment by lukaszgryglicki** [comment]
@jgbarah I'm working on the bigger deployment, created a specific repo and README [here](https://github.com/lukaszgryglicki/bitergia_deployment/blob/master/README.md).
Can you help me a bit with "mailing lists" data source? I need to get data from [Google Groups data source](https://groups.google.com/a/onosproject.org/forum/#!forum/onos-dev) and I don't know which data source should be used for this. They either require a directory with mbox files or URL to some services, but obviously not Google Groups. I don't have any mbox files from Google Groups and I don't know how to get them, maybe I should use on of 4 other mailing box data sources? 
[This](https://github.com/lukaszgryglicki/bitergia_deployment/blob/master/TODO.md) is what I know so far. This obviously can be done, because it works [here](https://onos.biterg.io/app/kibana#/dashboard/MailingLists?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-10y,mode:relative,to:now))&_a=(description:'Mailing%20Lists%20Overview%20panel%20by%20Bitergia',filters:!(),fullScreenMode:!f,options:(darkTheme:!f,useMargins:!t),panels:!((gridData:(h:2,i:'1',w:3,x:2,y:0),id:mbox_evolution_emails,panelIndex:'1',title:Emails,type:visualization,version:'6.1.0-3'),(gridData:(h:2,i:'2',w:3,x:2,y:2),id:mbox_evolution_participants,panelIndex:'2',title:'Email%20Senders',type:visualization,version:'6.1.0-3'),(gridData:(h:4,i:'3',w:2,x:0,y:0),id:mbox_main_numbers,panelIndex:'3',title:mbox,type:visualization,version:'6.1.0-3'),(gridData:(h:4,i:'4',w:3,x:5,y:0),id:mbox_organizations,panelIndex:'4',title:Organizations,type:visualization,version:'6.1.0-3'),(gridData:(h:4,i:'5',w:4,x:8,y:0),id:mbox_main_projects,panelIndex:'5',title:Projects,type:visualization,version:'6.1.0-3'),(gridData:(h:4,i:'6',w:5,x:0,y:4),id:mbox_main_participants,panelIndex:'6',title:'Email%20Senders',type:visualization,version:'6.1.0-3'),(gridData:(h:4,i:'7',w:7,x:5,y:4),id:mbox_organizations_evolutionary,panelIndex:'7',title:Organizations,type:visualization,version:'6.1.0-3'),(gridData:(h:3,i:'8',w:5,x:0,y:8),id:mbox_emails_timezone,panelIndex:'8',title:'Emails%20by%20Time%20Zone',type:visualization,version:'6.1.0-3'),(gridData:(h:3,i:'9',w:7,x:5,y:8),id:mbox_main_malinglists,panelIndex:'9',title:'Mailing%20Lists',type:visualization,version:'6.1.0-3')),query:(language:lucene,query:(query_string:(analyze_wildcard:!t,default_field:'*',query:'*'))),timeRestore:!f,title:'Mailing%20Lists',uiState:(P-1:(title:Emails,vis:(legendOpen:!f)),P-2:(title:'Email%20Senders',vis:(legendOpen:!f)),P-3:(title:mbox),P-4:(title:Organizations,vis:(legendOpen:!t)),P-5:(title:Projects,vis:(params:(config:(searchKeyword:''),sort:(columnIndex:!n,direction:!n)))),P-6:(title:'Email%20Senders',vis:(params:(config:(searchKeyword:''),sort:(columnIndex:!n,direction:!n)))),P-7:(title:Organizations),P-8:(title:'Emails%20by%20Time%20Zone',vis:(legendOpen:!f)),P-9:(title:'Mailing%20Lists',vis:(params:(config:(searchKeyword:''),sort:(columnIndex:!n,direction:!n))))),viewMode:view))

**Comment by jgbarah** [comment]
Yes, of course.

But in this case, I have little to say: Perceval knows how to retrieve messages from files in mbox format. Which AFAIK, is not provided by Google Groups. What we usually do is to subscribe a bot to the mailing list, to archive it in an mbox file, and analyze that mbox file. For past messages, you can in some cases locate somebody archiving the mailing list.

Probably there is some software out there to spider Google Groups, but afaik, it has not been used in combination with Perceval. I would be interested if you happen to advance in this direction.

**Comment by lukaszgryglicki** [comment]
I will, but don't know when yet. Thanks.

**Comment by lukaszgryglicki** [comment]
Update: [json2hat tool](https://github.com/cncf/json2hat) was moved to its own repository and updated.
- Added support for fetching affiliations JSON from a remote source (fallback when no local source is available)
- Added support for specifying both local and remote JSON source via environment variables
- Added support for setting sorting hat database parameters either via full connect string `SH_DSN` or by setting individual params via `SH_*` variables (or using default ones)
- Fixed bug when trying to update profile country code to the non-existing one (which caused foreign key violation and wasn't detected before because affiliations JSON was 4 times smaller)
- Fixed bug with company name collision when attempting to insert company name differing only by lower/upper case from the existing company (database company names are case insensitive in Sorting Hat MariaDB database).
- Packaged in a docker container
- Battle-tested with real MariaDB managed database (AWS) and remote-only [github_users.json](
https://github.com/cncf/gitdm/blob/master/github_users.json?raw=true) (40+ Mb) from [cncf/gitdm](https://github.com/cncf/gitdm)

**Comment by lukaszgryglicki** [comment]
cc @jgbarah
